name: Commit Check
on:
  push:
    branches:
      - ltrn
  pull_request:
jobs:
  check-commit-author:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dguo/check-author-and-committer-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          committer-email-regex: '^count\.epsilon@proton\.me|noreply@github\.com$'
          committer-name-regex: 'Count Epsilon|CountE|GitHub'
          author-email-regex: '^count\.epsilon@proton\.me$'
          author-name-regex: '^Count Epsilon|CountE$'
